[package]
name = "minigrep_vielenkz"
version = "0.1.2"
edition = "2021"
description = "An implementation of grep using rust"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 0

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
