[package]
name = "minigrep_vielenkz"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache 2.0"

[profile.dev]
opt-level = 0

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
